import requests

from django.conf import settings
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status

from courses.models.playlist import Playlist
from courses.serializers.playlist import PlaylistSerializer

AI_API_URL = 'https://api.openai.com/v1/chat/completions'
AI_MODEL = 'gpt-4o'


def _get_ai_token():
    return getattr(settings, 'AI_TOKEN', '')


def _call_ai(prompt: str) -> str:
    response = requests.post(
        AI_API_URL,
        headers={
            'Authorization': f'Bearer {_get_ai_token()}',
            'Content-Type': 'application/json',
        },
        json={
            'model': AI_MODEL,
            'messages': [
                {
                    'role': 'system',
                    'content': (
                        'You are an intelligent learning assistant for an educational platform. '
                        'Give concise, practical, personalised advice based on the user profile provided.'
                    ),
                },
                {'role': 'user', 'content': prompt},
            ],
            'temperature': 0.7,
            'max_tokens': 512,
        },
        timeout=20,
    )
    response.raise_for_status()
    return response.json()['choices'][0]['message']['content'].strip()


class AIRecommendView(APIView):
    """
    POST /api/ai/recommend/

    Returns AI-powered playlist recommendations based on the user's skills and field.
    Requires: Authorization: Bearer <AI_TOKEN>
    Body (optional): { "limit": 5 }
    """

    def post(self, request):
        if not _get_ai_token():
            return Response({'detail': 'AI service is not configured.'}, status=status.HTTP_503_SERVICE_UNAVAILABLE)

        user = request.user if request.user.is_authenticated else None
        skills, field = [], ''

        if user:
            try:
                skills = user.onboarding.skills or []
                field = user.onboarding.field or ''
            except Exception:
                pass

        limit = min(int(request.data.get('limit', 6)), 10)

        qs = Playlist.objects.all()
        if skills:
            qs = qs.filter(tags__name__in=skills).distinct()
        playlists = list(qs[:limit])

        playlist_titles = ', '.join(p.title for p in playlists) or 'various topics'
        prompt = (
            f'The user is interested in "{field or "General Programming"}" '
            f'and has skills in: {", ".join(skills) or "not specified"}. '
            f'We are recommending these playlists: {playlist_titles}. '
            f'Write 1-2 sentences explaining why these playlists are a good fit for this user.'
        )

        try:
            message = _call_ai(prompt)
        except Exception as exc:
            return Response({'detail': f'AI service error: {exc}'}, status=status.HTTP_502_BAD_GATEWAY)

        serializer = PlaylistSerializer(playlists, many=True, context={'request': request})

        return Response({
            'status': 'ok',
            'result': {
                'message': message,
                'playlists': serializer.data,
            },
        })


class AILearningPathView(APIView):
    """
    POST /api/ai/learning-path/

    Returns a structured learning path generated by AI for the user's field and level.
    Requires: Authorization: Bearer <AI_TOKEN>
    Body (optional): { "field": "Python", "level": "beginner" }
    """

    def post(self, request):
        if not _get_ai_token():
            return Response({'detail': 'AI service is not configured.'}, status=status.HTTP_503_SERVICE_UNAVAILABLE)

        user = request.user if request.user.is_authenticated else None
        field = request.data.get('field', '')
        level = request.data.get('level', 'beginner')

        if not field and user:
            try:
                field = user.onboarding.field or ''
            except Exception:
                pass

        prompt = (
            f'Create a structured learning path for someone interested in "{field or "General Programming"}" '
            f'at a {level} level. Return a JSON object with keys: '
            f'"advice" (string), "path" (array of objects with "step", "focus", "estimated_weeks"), '
            f'"total_estimated_weeks" (number). Return only valid JSON, no extra text.'
        )

        try:
            ai_response = _call_ai(prompt)
            import json
            result = json.loads(ai_response)
        except Exception as exc:
            return Response({'detail': f'AI service error: {exc}'}, status=status.HTTP_502_BAD_GATEWAY)

        result['field'] = field or 'General Programming'
        result['level'] = level

        return Response({'status': 'ok', 'result': result})


class AIAdviceView(APIView):
    """
    POST /api/ai/advice/

    Returns personalised skill advice generated by AI for the authenticated user.
    Requires: Authorization: Bearer <AI_TOKEN>
    """

    def post(self, request):
        if not _get_ai_token():
            return Response({'detail': 'AI service is not configured.'}, status=status.HTTP_503_SERVICE_UNAVAILABLE)

        user = request.user if request.user.is_authenticated else None
        skills, field, occupation = [], '', ''

        if user:
            try:
                skills = user.onboarding.skills or []
                field = user.onboarding.field or ''
                occupation = user.onboarding.occupation or ''
            except Exception:
                pass

        prompt = (
            f'The user works as "{occupation or "not specified"}", '
            f'is interested in "{field or "General Programming"}", '
            f'and currently has skills in: {", ".join(skills) or "none listed"}. '
            f'Return a JSON object with keys: '
            f'"field_advice" (string), "skill_tips" (array of strings, max 3), '
            f'"next_action" (string). Return only valid JSON, no extra text.'
        )

        try:
            ai_response = _call_ai(prompt)
            import json
            result = json.loads(ai_response)
        except Exception as exc:
            return Response({'detail': f'AI service error: {exc}'}, status=status.HTTP_502_BAD_GATEWAY)

        result['field'] = field or 'General Programming'
        result['occupation'] = occupation or 'Not specified'
        result['skills_detected'] = skills

        return Response({'status': 'ok', 'result': result})
