# Generated by Django 5.2.12 on 2026-03-04 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('subscribers', models.CharField(blank=True, max_length=20)),
                ('avatar_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#ffffff', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('video_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlists', to='courses.channel')),
                ('tags', models.ManyToManyField(blank=True, related_name='playlists', to='courses.tag')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='channels', to='courses.tag'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('duration', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='courses.channel')),
                ('tags', models.ManyToManyField(blank=True, related_name='videos', to='courses.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('content_type', models.CharField(choices=[('playlist', 'Playlist'), ('video', 'Video'), ('channel', 'Channel')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('channels', models.ManyToManyField(blank=True, related_name='sections', to='courses.channel')),
                ('playlists', models.ManyToManyField(blank=True, related_name='sections', to='courses.playlist')),
                ('videos', models.ManyToManyField(blank=True, related_name='sections', to='courses.video')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'content_type', 'object_id')},
            },
        ),
    ]
