# Generated by Django 5.2.12 on 2026-03-04 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookmark',
            options={'verbose_name': 'Закладка', 'verbose_name_plural': 'Закладки'},
        ),
        migrations.AlterModelOptions(
            name='channel',
            options={'verbose_name': 'Канал', 'verbose_name_plural': 'Каналы'},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'verbose_name': 'Плейлист', 'verbose_name_plural': 'Плейлисты'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['order'], 'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Видео', 'verbose_name_plural': 'Видео'},
        ),
        migrations.AddField(
            model_name='section',
            name='field',
            field=models.CharField(blank=True, help_text='Оставьте пустым чтобы показывать всем пользователям', max_length=100, verbose_name='Направление (фильтр)'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип объекта'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='ID объекта'),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='avatar_url',
            field=models.URLField(blank=True, verbose_name='Аватар (URL)'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название канала'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='subscribers',
            field=models.CharField(blank=True, max_length=20, verbose_name='Подписчики'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='channels', to='courses.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='url',
            field=models.URLField(blank=True, verbose_name='Ссылка на канал'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='youtube_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='YouTube ID'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playlists', to='courses.channel', verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='playlists', to='courses.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='thumbnail_url',
            field=models.URLField(blank=True, verbose_name='Обложка (URL)'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='video_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество видео'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='youtube_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='YouTube ID'),
        ),
        migrations.AlterField(
            model_name='section',
            name='channels',
            field=models.ManyToManyField(blank=True, related_name='sections', to='courses.channel', verbose_name='Каналы'),
        ),
        migrations.AlterField(
            model_name='section',
            name='content_type',
            field=models.CharField(choices=[('playlist', 'Плейлист'), ('video', 'Видео'), ('channel', 'Канал')], max_length=20, verbose_name='Тип контента'),
        ),
        migrations.AlterField(
            model_name='section',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='section',
            name='playlists',
            field=models.ManyToManyField(blank=True, related_name='sections', to='courses.playlist', verbose_name='Плейлисты'),
        ),
        migrations.AlterField(
            model_name='section',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='section',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='section',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='sections', to='courses.video', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7, verbose_name='Цвет (HEX)'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='video',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='courses.channel', verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='video',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.CharField(blank=True, max_length=20, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='videos', to='courses.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail_url',
            field=models.URLField(blank=True, verbose_name='Обложка (URL)'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='YouTube ID'),
        ),
    ]
