# Generated by Django 5.2.12 on 2026-03-07 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_bookmark_options_alter_channel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='duration',
            field=models.CharField(blank=True, max_length=50, verbose_name='Продолжительность (напр. 5h 35m)'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='lang',
            field=models.CharField(blank=True, max_length=50, verbose_name='Язык курса (напр. En/Англ)'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='language',
            field=models.CharField(blank=True, max_length=100, verbose_name='Язык программирования (напр. Python)'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='what_you_will_learn',
            field=models.TextField(blank=True, verbose_name='Что вы узнаете? (каждая строка — пункт)'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='why_this_course',
            field=models.TextField(blank=True, verbose_name='Почему этот курс? (каждая строка — пункт)'),
        ),
    ]
