# Generated by Django 5.2.12 on 2026-03-20 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_playlist_detail_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Показывать'),
        ),
    ]
