# Generated by Django 5.2.12 on 2026-04-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_add_is_visible_to_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='Избранный (главная)'),
        ),
    ]
