# Generated by Django 5.2.12 on 2026-03-04 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(blank=True, max_length=100, verbose_name='Направление')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='Профессия')),
                ('skills', models.JSONField(default=list, verbose_name='Навыки')),
                ('current_step', models.PositiveSmallIntegerField(default=0, verbose_name='Текущий шаг')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Онбординг пользователя',
                'verbose_name_plural': 'Онбординг пользователей',
            },
        ),
    ]
